pipelines:
  - name: automation_demo_PDE
    steps:
      - name: demoZstepAAAAAAAAAA
        type: Bash
        configuration: 
          environmentVariables:
            MY_ENV: "HifromENV"
        execution:
          onExecute: 
            - echo "on Excute $MY_ENV "
          onFailure:
            - echo "on fail success"
          onSuccess:
            - echo "on Success"
          onComplete:
            - echo "on complete"
# pipelines:
#  - name: viren_demo
#    steps:
#     - name: demo_step_trigger
#       type: Bash
#       execution:
#        onExecute:
#         - echo "trigger" #green
#     - name: demo_step_one
#       type: Bash
#       configuration:
#        inputSteps:
#         - demo_step_trigger      
#       execution:
#        onExecute:
#         - fgrtytjrergdgn #red
#        onFailure: 
#         - echo "OnFail log" #green
#        onComplete: 
#         - echo "onComplete log" #green
#     - name: demo_step_two
#       type: Bash
#       configuration:
#        inputSteps:
#         - demo_step_trigger      
#       execution:
#        onExecute:
#         - echo "hello world"
#        onSuccess:
#         - dofnbonod5543 #red     
#     - name: demo_step_three 
#       type: Bash
#       configuration:
#        inputSteps:
#         - demo_step_trigger      
#       execution:
#        onExecute:
#         - echo "hello world"
#        onComplete:
#         - dofnbonod5543  #red 
#     - name: demo_step_four
#       type: Bash
#       configuration:
#        inputSteps:
#         - demo_step_trigger      
#       execution:
#        onExecute:
#         - fgrtytjrergdgn
#        onFailure: 
#         - rbtebtedbe #red
#     - name: demo_step_five
#       type: Bash
#       configuration:
#        inputSteps:
#         - demo_step_trigger      
#       execution:
#        onExecute:
#         - echo "hello world"
#        onSuccess:
#         - echo "onsuccess" #green            
