pipelines:
 - name: viren_demo
   steps:
    - name: demo_step
      type: Bash
      execution:
       onExecute:
        - echo "Hello World!"
    - name: demo_second_step
       type: Bash
       execution:
        onExecute:
         - echo "Hello world 2"    